data:
  menus:
    - name: 项目
      id: project
      path: /project
      icon: OrderedListOutlined
      perms:
        - perm: project:view
          name: 查看
        - perm: project:save
          name: 保存
        - perm: project:delete
          name: 删除
        - perm: project:build
          name: 构建
    - name: 应用
      id: app
      path: /app
      icon: AppstoreOutlined
    - name: 其他
      id: config
      icon: SettingOutlined
      children:
        - name: 主机
          id: host
          path: /host
          icon: DesktopOutlined
          perms:
            - perm: host:view
              name: 查看
            - perm: host:save
              name: 保存
            - perm: host:delete
              name: 删除
        - name: 应用分组
          id: appGroup
          path: /app-group
          icon: ClusterOutlined
          perms:
              - perm: appGroup:save
                name: 保存
              - perm: appGroup:delete
                name: 删除
              - perm: appGroup:view
                name: 查看
