services:
  admin:
    image: registry.cn-hangzhou.aliyuncs.com/jiangood/docker-admin
    ports:
      - "7001:7001"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data/:/data"

